version: "3.8"
services:
  db:
    image: postgres:16-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=excalidraw-refined
      - POSTGRES_USER=excalidraw-refined
      - POSTGRES_PASSWORD=excalidraw-refined
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "excalidraw-refined" ]

  frontend:
    image: ghcr.io/iamshobe/excalidraw-refined_frontend:latest

  run-migrations:
    image: ghcr.io/iamshobe/excalidraw-refined_backend:latest
    environment:
      - DB_URL=postgresql://excalidraw-refined:excalidraw-refined@db:5432/excalidraw-refined
    entrypoint: [ "alembic", "upgrade", "head" ]
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: ghcr.io/iamshobe/excalidraw-refined_backend:latest
    environment:
      - DB_URL=postgresql://excalidraw-refined:excalidraw-refined@db:5432/excalidraw-refined
    command:
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
    depends_on:
      db:
        condition: service_healthy
      run-migrations:
        condition: service_completed_successfully

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - FRONTEND_PORT=80
      - BACKEND_PORT=8080
    depends_on:
      - frontend
      - backend
