version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  run-migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      - DB_URL=sqlite:////data/db.sqlite
    entrypoint: [ "alembic", "upgrade", "head" ]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      - DB_URL=sqlite:////data/db.sqlite
    command:
      - --host
      - "0.0.0.0"
      - --port
      - "8080"
    depends_on:
      run-migrations:
        condition: service_completed_successfully

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
