/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyAuthJwtLoginAuthJwtLoginPostClientId } from './bodyAuthJwtLoginAuthJwtLoginPostClientId';
import type { BodyAuthJwtLoginAuthJwtLoginPostClientSecret } from './bodyAuthJwtLoginAuthJwtLoginPostClientSecret';
import type { BodyAuthJwtLoginAuthJwtLoginPostGrantType } from './bodyAuthJwtLoginAuthJwtLoginPostGrantType';

export interface BodyAuthJwtLoginAuthJwtLoginPost {
  client_id?: BodyAuthJwtLoginAuthJwtLoginPostClientId;
  client_secret?: BodyAuthJwtLoginAuthJwtLoginPostClientSecret;
  grant_type?: BodyAuthJwtLoginAuthJwtLoginPostGrantType;
  password: string;
  scope?: string;
  username: string;
}
