/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SceneSummary } from './sceneSummary';
import type { CursorPageSceneSummaryNextCursor } from './cursorPageSceneSummaryNextCursor';

export interface CursorPageSceneSummary {
  count: number;
  items: SceneSummary[];
  limit: number;
  next_cursor: CursorPageSceneSummaryNextCursor;
  total: number;
}
