/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface SceneSummary {
  created: string;
  description: string;
  id: string;
  last_updated: string;
  name: string;
  picture: string;
  revision_id: string;
}
