apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw-refined.fullname" . }}-backend
  labels:
    app.kubernetes.io/component: backend
    {{- include "excalidraw-refined.labels" . | nindent 4 }}
spec:
  type: {{ .Values.applications.backend.service.type }}
  ports:
    - port: {{ .Values.applications.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: backend
    {{- include "excalidraw-refined.selectorLabels" . | nindent 4 }}
