apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "excalidraw-refined.fullname" . }}-migrations
  labels:
    {{- include "excalidraw-refined.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "excalidraw-refined.fullname" . }}-migrations
      labels:
        {{- include "excalidraw-refined.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: migrations
        image: "{{ .Values.applications.backend.image.repository }}:{{ .Values.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.applications.backend.image.pullPolicy }}
        command: {{ toJson .Values.applications.backend.migrations.command }}
        env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "excalidraw-refined.dbSecretName" . }}
                key: {{ include "excalidraw-refined.dbSecretKey" . }}
