{{- range $component, $componentValues := $.Values.deployments }}
{{- if $componentValues.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "excalidraw-refined.serviceAccountName" $ }}-{{ $component }}
  labels:
    app.kubernetes.io/component: {{ $component}}
    {{- include "excalidraw-refined.labels" $ | nindent 4 }}
  {{- with $componentValues.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}