"""add indexes

Revision ID: 0e27910c4854
Revises: 03eb4b53ce62
Create Date: 2024-01-24 15:46:06.121110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e27910c4854'
down_revision: Union[str, None] = '03eb4b53ce62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scenes_created'), 'scenes', [sa.text('created DESC')], unique=False)
    op.create_index(op.f('ix_scenes_name'), 'scenes', ['name'], unique=False)
    op.create_index(op.f('ix_scenes_updated'), 'scenes', [sa.text('updated DESC')], unique=False)
    op.create_index(op.f('ix_scenes_revisions_created'), 'scenes_revisions', [sa.text('created DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_revisions_created'), table_name='scenes_revisions')
    op.drop_index(op.f('ix_scenes_updated'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_name'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_created'), table_name='scenes')
    # ### end Alembic commands ###
