"""add description column to scene

Revision ID: c89365667a49
Revises: b8b6c3e875b2
Create Date: 2024-01-23 15:17:14.127153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89365667a49'
down_revision: Union[str, None] = 'b8b6c3e875b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenes', sa.Column('description', sa.String(length=512), nullable=False, server_default=""))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'description')
    # ### end Alembic commands ###
